language: ruby
rvm:
  - 2.3.1

addons:
  postgresql: "9.4"

services:
  - postgresql

bundler_args: --without development --deployment --jobs=3 --retry=3
cache: bundler

before_script:
  - psql -c 'create database stackowf_test;' -U postgres
  - cp config/database.yml.example config/database.yml
  - bundle exec rake db:setup

gemfile:
  - Gemfile
